- content: 'Off-season organic vegetable and fruit production.'

- content: 'Organic vegetable and agriculture seed production.'

- content: 'Indigenous vegetable farming techniques.'

- content: 'Indigenous fruit farming techniques.'

- content: 'Indigenous post harvest technologies in fruit and vegetable crops.'

- content: 'Minimum village and minimum watering technologies in fruit and vegetable farming.'

- content: 'Plastic house production technologies of high value crops.'

- content: 'Participatory development activities and social mobilization techniques.'

- content: 'Awareness creating techniques.'
